import Head from 'next/head'
import Image from 'next/image'
import { AppShell, Text, Input, Container, Button } from '@mantine/core'
import { useState, useEffect } from 'react'
import { io } from 'socket.io-client'
import axios from 'axios'
// import Chat from '../components/chat'
let socket


export default function Home() {
  useEffect(() => {
    socketInitializer()
  }, [])
    const socketInitializer = async () => {
      await axios.get('/api/socket')
      socket = io()
      socket.on('connect', () => {
        console.log('connected')
      })
      socket.on('update-input', msg => {
        setTest(msg)
      })
    }
  const [user, setUser] = useState()
  const [test, setTest] = useState()
  function testChange(e) {
    setTest(e)
    socket.emit('input-change', e)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
      >
        <Input onChange={e => testChange(e.target.value)} value={test}/>
        {/* { user ? <chat user={user}/> : <Login setuser={setUser}/>} */}
      </AppShell>
    </>
  )
}

function Login({setuser}){
  const [name, setName] = useState()
  return(
    <Container size={300}>
      <Input placeholder='Input name' onChange={(e) => setName(e.target.value)} />
      <Button onClick={() => setuser(name)}>Submit</Button>
    </Container>
  )
}